//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public class ActeMedical
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActeMedical()
        {
           
        }
        
        public int ActeMedicalId { get; set; }
        public int DMDPatientId { get; set; }
        public int FactureId { get; set; }
       
        public virtual DMDPatient DMDPatient { get; set; }
        public virtual Facture Facture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentComplementaire> DocumentComplementaire { get; set; }

        public int RendezVousId { get; set; }
        public virtual RendezVous RendezVous { get; set; }

        
        public string Traitement { get; set; }
    }
}
