//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class Consultation : ActeMedical
    {
        public int ConsultationId { get; set; }

        
        public string MotifConsultation { get; set; }

        
        public string HistoireMaladie { get; set; }

        
        public string ExamenClinique { get; set; }

        
        public string DiagnostiqueFinal { get; set; }

        
        public string traitementPropose { get; set; }
    }
}
