//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class DMDPatient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMDPatient()
        {
            this.ActeMedical = new HashSet<ActeMedical>();
          
        }
    
        public int DMDPatientId { get; set; }

        
        public string NomPatient { get; set; }

        
        public string PrenomPatient { get; set; }

        
        public int TelPatient { get; set; }

        
        public string MailPatient { get; set; }

        
        public string AdressePatient { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime DateDeNaissance { get; set; }

        
        public string AntecedentsFamiliaux { get; set; }

        
        public string AntecedentsPersonnel { get; set; }

        
       

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActeMedical> ActeMedical { get; set; }
        
    }
}
