//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class DocumentComplementaire
    {
        public int DocumentComplementaireId { get; set; }
        public int ActeMedicalId { get; set; }
        public virtual ActeMedical ActeMedical { get; set; }

        
        public string TypeDocumnet { get; set; }
        
        public string TitreDocument { get; set; }

        
        public string contenuDocument { get; set; }

        
        public string Avis { get; set; }
    }
}
