//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class Facture
    {
        public int FactureId { get; set; }
        public int ActeMedicalId { get; set; }
        public virtual ActeMedical ActeMedical { get; set; }

        
        public Boolean EtatReglement { get; set; }

        
        public int Montant { get; set; }
    }
}
